### ISSUE TITLE
'strtmnth' can't be converted from string to numeric in years >= 2010

### ISSUE THREAD

**Issue by polarimetric** [arcenis-r/cepumd#1]
Hi, thanks for the excellent package--has certainly saved me a lot of time trying to navigate the CEX.

I'm having an issue with the diary files for years after 2010 with the "strtmnth" variable from the household file. Years from 2002 to 2009 work without incident, but starting in 2010, when keeping the "strtmnth" variable in the final dataset, I get the following error:

`Error: Column strtmnth can't be converted from character to numeric`

Here is the exact code I ran:

`data <- setDT(ce_prepdata(year=yr, survey='diary', zp=NULL, integrate_data=FALSE, uccs=uccs, stub=stub, recode_variables=TRUE, sex_ref, age_ref, ref_race, marital1, fam_size, fam_type, state, strtmnth, weeki, weekn))`

I read in the FMLD files from the 2010 survey manually and `as.numeric(strtmnth)` seemed to be fine there, so I'm not sure about the cause.

**Comment by arcenis-r** [comment]
Thanks for calling this out. I suspect that my recent update will have taken care of this, but I'll take a look at this in the next day or 2 and get back to you. Also, I'm very sorry for my delay in responding. My knowledge of GitHub as a social coding platform prior to a few days ago was embarrassingly paltry.

**Comment by arcenis-r** [comment]
I ran the following code to try and replicate the error with strtmnth, but got no error. It may be that my recent update of ce_prepdata() resolved it, but please try it again and let me know if you still get the error and I'll look into it again. I'm going to close the issue, but please request to reopen if your issue wasn't solved.

`pet_uccs <- ce_uccs(ce_hg(2010, diary), "Pets", uccs_only = TRUE)

diary10 <- ce_prepdata(
  2010,
  diary,
  pet_uccs,
  recode_variables = FALSE,
  ce_dir = NULL,
  own_codebook = NULL,
  dict_path = NULL,
  int_zp = NULL,
  dia_zp = NULL,
  hg = ce_hg(2010, diary),
  strtmnth
)`
