### ISSUE TITLE
ce_uccs() returns too many uccs for certain expenditure categories

### ISSUE THREAD

**Issue by awunderground** [arcenis-r/cepumd#2]
Consider this stub from 2015.

![uccs](https://user-images.githubusercontent.com/11818850/71698127-4f739b00-2d88-11ea-862f-0a94b3d550b7.PNG)

I would expect the following code to return `[1] "190321" "190322" "190323" "190324"`.

```
stub_file <- cepumd::ce_stub(2015, integrated)

cepumd::ce_uccs(stub_file, "Breakfast and brunch")
```
Instead, it returns 

`[1] "190321" "190322" "190323" "190324" "190901" "190902" "190903" "790430" "800700" "200111" "200210" "200310" "200410"`

That's because `ce_uccs()` can't handle cases where the level decreases by more than one (from line 171 to 172). Here:

```
  stop_row <- match(
    title_row_level,
    stub$level[(title_row + 1):(nrow(stub) - 1)]
  ) + title_row - 1
```

**Comment by awunderground** [comment]
I'll put in a pull request with the solution now. 

```
stop_row <- match(
      TRUE,
      title_row_level >= stub$level[(title_row + 1):(nrow(stub))] # all remaining levels
    ) + title_row - 1
```

**Comment by arcenis-r** [comment]
Thank you! I used your solution, but did not do it through a pull request because the reference to "stub" has now changed to "hg" and it would've been messier to do it as a pull (I think). The issue should be resolved now, though. Please feel free to reopen if you notice that it hasn't been.
