### ISSUE TITLE
Installation directions 

### ISSUE THREAD

**Issue by BenjaminKay** [arcenis-r/cepumd#4]
The file "README.md" says that to install the package you should run the following:
    devtools::install_github("/arcenis-r/cepumd")
However, this code doesn't work for me. Checking against other install_github examples, I changed the code to the following (notice no leading "/") and now it works. I recommend changing the directions. 
    devtools::install_github("arcenis-r/cepumd")

**Comment by arcenis-r** [comment]
Thank you for calling this out, I've recently changed this in the README file.
