### ISSUE TITLE
SE does not match tables

### ISSUE THREAD

**Issue by socosco** [arcenis-r/cepumd#6]
The SE calculation does not match what CES publishes in the tables. Even for the example, with pets, the SE does not match. In the example it comes out to 25.73933 when it is 43.19 in the CES table for 2018. https://www.bls.gov/cex/tables/calendar-year/mean/cu-all-detail-2018.pdf

**Comment by arcenis-r** [comment]
The SE will never match the tables. Table estimates and SEs are calculated using internal, confidential data, where as the public only has access to the Public-Use Microdata. Please see the CE's disclosure page for more on this issue: https://www.bls.gov/cex/pumd_disclosure.htm. I'll consider this issue closed. If you have any more questions regarding differences in the calculations, please contact the Consumer Expenditure Surveys program or review their documentation.
